check ci/cd for polybot

diff --git a/.github/workflows/polybot-deployment.yaml b/.github/workflows/polybot-deployment.yaml
--- a/.github/workflows/polybot-deployment.yaml
+++ b/.github/workflows/polybot-deployment.yaml
@@ -19,6 +19,7 @@ jobs:
           cd polybot
           
           # TODO your implementation here....
+          docker login -u ${{ secrets.DOCKER_REPO_USERNAME }} -p ${{ secrets.DOCKER_REPO_PASSWORD }}
           POLYBOT_IMAGE=maayanassraf/polybot-aws-project:${{ github.run_number }}
           docker build -t $POLYBOT_IMAGE .
           docker push $POLYBOT_IMAGE
@@ -33,5 +34,27 @@ jobs:
         uses: actions/checkout@v2
       - name: Deploy new version
         run: |         
-          # TODO your implementation here....     
-     
+          POLYBOT_IMAGE=maayanassraf/polybot-aws-project:${{ github.run_number }}
+          # gets ip from polybot ec2 by their tags.    
+          POLYBOT_SERVERS_IP = $(aws ec2 describe-instances  --filters "Name=tag:App,Values=Maayan-polybot" --query 'Reservations[*].Instances[*].[PublicIpAddress]' --output text)
+          # do the needed actions for every ec2 if its on (has public ip)
+          for SERVER_IP in $(echo $polybot_servers); 
+          do 
+            if [[ $SERVER_IP =~ [0-9] ]]; 
+            then 
+              # connect to ec2
+              echo ${{ secrets.EC2_SSH_PRIVATE_KEY }} > private_key && chmod 600 private_key
+              ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${SERVER_IP}
+                # deploys new polybot version
+                docker ps | grep polybot
+                if [ $? -eq 0 ]
+                then
+                  docker stop polybot
+                  docker rm polybot
+                fi
+                docker run -p 8443:8443 --restart always --name polybot $POLYBOT_IMAGE
+                if [ $? -ne 0 ]
+                then
+                  echo "docker run operation has failed in $SERVER_IP"
+            fi;
+          done
