changed tf with needed outputs

diff --git a/.github/workflows/yolo5-deployment-region.yaml b/.github/workflows/yolo5-deployment-region.yaml
--- a/.github/workflows/yolo5-deployment-region.yaml
+++ b/.github/workflows/yolo5-deployment-region.yaml
@@ -23,9 +23,60 @@ jobs:
     steps:
       - name: Checkout the repo code
         uses: actions/checkout@v2
+
+      - name: Get Yolo5 EC2's IP
+        env:
+          AWS_DEFAULT_REGION: ${{ inputs.region-code }}
+        run: |
+          # Allows running aws commands
+          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
+          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
+          # Gets instances id from polybot ec2 by their tags
+          INSTANCES_IDS=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=maayana-yolo5-ec2" \
+            --query 'Reservations[*].Instances[*].{InstanceId:InstanceId}' \
+            --output text)
+
+          for instance_id in $INSTANCES_IDS;
+          do
+            state=$(aws ec2 describe-instances --filters "Name=instance-id,Values=$instance_id" \
+              --query 'Reservations[*].Instances[*].{State:State.Name}' \
+              --output text)
+
+            echo "The instance - $instance_id is in state - $state"
+
+            if [ "$state" = "terminated" ]; 
+            then
+              echo "Instance terminated, cannot be started..."
+            elif [ "$state" = "stopped" ]; 
+            then
+              echo "Starting instance..."
+              aws ec2 start-instances --instance-ids $instance_id
+
+              # Waits until the instance is running
+              aws ec2 wait instance-running --instance-ids $instance_id
+            else
+              echo "Instance already running, skipping..."
+            fi
+          done
+
+          # Gets public ip from yolo5 ec2 by their tags (Gets only from running EC2s).
+          YOLO5_SERVERS_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=maayana-yolo5-ec2" \
+          --query 'Reservations[*].Instances[*].[PublicIpAddress]' \
+          --output text | grep -v None)
+          echo "The IPs of running Yolo5 EC2's are- $YOLO5_SERVERS_IP"
+
+          # Writes the YOLO5_SERVERS_IP to github env- for using in another step
+          {
+          echo 'YOLO5_SERVERS_IP<<EOF'
+          echo "$YOLO5_SERVERS_IP"
+          echo EOF
+          } >> "$GITHUB_ENV"
+
       - name: Deploy new version
         env:
           AWS_DEFAULT_REGION: ${{ inputs.region-code }}
+          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
         run: |
           cd tf 
           # Gets from tfvars file the owner name
@@ -40,57 +91,39 @@ jobs:
           DYNAMODB_TABLE=tf-$OWNER-predictions-dynamodb-table
           ALB_URL=$OWNER-polybot-$AWS_DEFAULT_REGION.int-devops.click:8443" | tr -d ' ' > .env
           
-          cd yolo5
+          # Gets from env only the IPs
+          YOLO5_SERVERS_IP=${YOLO5_SERVERS_IP#*:}
+          echo "The IPs of running Yolo5 EC2's are- $YOLO5_SERVERS_IP"
           
-          # Allows running aws commands
-          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
-          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          export YOLO5_IMAGE=maayanassraf/yolo5-aws-project:latest
+          echo "polybot image - $YOLO5_IMAGE"
           
-          YOLO5_IMAGE=maayanassraf/yolo5-aws-project:${{ github.run_number }}
+          # Creates from secret the private key as file.
+          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
 
-#          # Saves new user-data as base64 (includes new yolo5 image) for using in new launch template version
-#
-#          DATA_BASE64=$(echo -n "#!/bin/bash
-#          # Add Docker's official GPG key:
-#          sudo apt-get update
-#          sudo apt-get install ca-certificates curl -y
-#          install -m 0755 -d /etc/apt/keyrings
-#          curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
-#          chmod a+r /etc/apt/keyrings/docker.asc
-#
-#          # Add the repository to Apt sources:
-#          echo \
-#            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
-#            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
-#            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-#          sudo apt-get update
-#
-#          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
-#
-#          sudo usermod -a -G docker ubuntu
-#          newgrp docker
-#
-#          docker run --restart always --name yolo5 $YOLO5_IMAGE" | base64)
-
-          # Gets the last launch template version (for using as source version at new launch template
-#          OLD_LT_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-id lt-0d51076c34836cbcc \
-#          --versions $Latest | jq '.LaunchTemplateVersions[] .VersionNumber' |  wc -l)
-#          echo "The last launch template version is $OLD_LT_VERSION (before creating new launch template)"
-#
-#          # Creates new launch template, based on the last launch template exists.
-#          aws ec2 create-launch-template-version --launch-template-id lt-0d51076c34836cbcc \
-#          --source-version $OLD_LT_VERSION --launch-template-data "UserData=$DATA_BASE64"
-#
-#          # Gets the new launch template version
-#          LT_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-id lt-0d51076c34836cbcc \
-#          --versions $Latest | jq '.LaunchTemplateVersions[] .VersionNumber' |  wc -l)
-#          echo "The new launch template version is $LT_VERSION (after creating new launch template)"
-#
-#          # Sets the new launch template as default version
-#          aws ec2 modify-launch-template --launch-template-id lt-0d51076c34836cbcc --default-version $LT_VERSION
-#
-#          # Starts an instance refresh for updating existing instances
-#          aws autoscaling start-instance-refresh --auto-scaling-group-name maayana-yolo5-asg --preferences '{"InstanceWarmup": 300, "MinHealthyPercentage": 50}'
-
+          # Do the needed actions for every ec2 if its on (has public ip)
+          for SERVER_IP in $(echo $YOLO5_SERVERS_IP); 
+          do
+            # Copies .env file to ec2
+            scp -o StrictHostKeyChecking=no -i private_key .env ubuntu@${SERVER_IP}:/home/ubuntu/
+            # Connects to ec2
+            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${SERVER_IP} <<EOF
+              YOLO5_IMAGE=maayanassraf/yolo5-aws-project:latest
+              echo $YOLO5_IMAGE
+              # Deploys new polybot version and stops older version (if exists)
+              docker ps | grep yolo5 
+              if [ $? -eq 0 ]
+              then
+                docker stop yolo5 
+                docker rm yolo5 
+              fi 
+              # Starts new docker container from new image
+              docker run -d --restart always --env-file .env --name yolo5 $YOLO5_IMAGE
+              if [ $? -ne 0 ]
+              then
+                echo "docker run operation has failed in $SERVER_IP"
+              fi
+          EOF
+          done
 
 
